name: dart_format
description: Formatting dart source files 
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies: 
  tuple: ^2.0.0
